"""Add is_banned column to User

Revision ID: 1b2878fcf04f
Revises: 
Create Date: 2025-11-14 01:13:58.586662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2878fcf04f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_is_banned'), 'users', ['is_banned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_banned'), table_name='users')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
